// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Wn-ly7nVRb3NiQsDe2c8eEP7H1SZ2uE',
    appId: '1:350138257109:web:8712f73ccec2c322011c5c',
    messagingSenderId: '350138257109',
    projectId: 'penggilingan-bumbu',
    authDomain: 'penggilingan-bumbu.firebaseapp.com',
    storageBucket: 'penggilingan-bumbu.firebasestorage.app',
    measurementId: 'G-KF0TS3YQK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXwsUsX6rx69p8rpDX8YSUNvZy51G8tn0',
    appId: '1:350138257109:android:fd6ba8f779e70b5f011c5c',
    messagingSenderId: '350138257109',
    projectId: 'penggilingan-bumbu',
    storageBucket: 'penggilingan-bumbu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KoZt9FpXsO4fcGyMBhIJpG6OcszwLYg',
    appId: '1:350138257109:ios:e1e5768c19899b5f011c5c',
    messagingSenderId: '350138257109',
    projectId: 'penggilingan-bumbu',
    storageBucket: 'penggilingan-bumbu.firebasestorage.app',
    iosBundleId: 'com.example.pelangganPenggilingan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3KoZt9FpXsO4fcGyMBhIJpG6OcszwLYg',
    appId: '1:350138257109:ios:e1e5768c19899b5f011c5c',
    messagingSenderId: '350138257109',
    projectId: 'penggilingan-bumbu',
    storageBucket: 'penggilingan-bumbu.firebasestorage.app',
    iosBundleId: 'com.example.pelangganPenggilingan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Wn-ly7nVRb3NiQsDe2c8eEP7H1SZ2uE',
    appId: '1:350138257109:web:28afb5668737472f011c5c',
    messagingSenderId: '350138257109',
    projectId: 'penggilingan-bumbu',
    authDomain: 'penggilingan-bumbu.firebaseapp.com',
    storageBucket: 'penggilingan-bumbu.firebasestorage.app',
    measurementId: 'G-WFEVMJ3EFW',
  );
}
